export interface Judgment {
  id: string;
  name: string;
  citation: string;
  court: string;
  year: number;
  topics: string[];
  holding_en: string;
  holding_hi: string;
  section?: string;
}

export const judgments: Judgment[] = [
  { id:'j1', name:'Kesavananda Bharati v. State of Kerala', citation:'AIR 1973 SC 1461', court:'Supreme Court', year:1973, topics:['Constitution','Basic Structure'], section:'Art.368', holding_en:'Parliament cannot amend the basic structure of the Constitution. Fundamental rights, separation of powers, judicial review form the basic structure.', holding_hi:'संसद संविधान के मूल ढाँचे का संशोधन नहीं कर सकती। मूल अधिकार, शक्तियों का पृथक्करण और न्यायिक पुनरावलोकन मूल ढाँचे का हिस्सा हैं।' },
  { id:'j2', name:'Maneka Gandhi v. Union of India', citation:'AIR 1978 SC 597', court:'Supreme Court', year:1978, topics:['Article 21','Personal Liberty','Due Process'], section:'Art.21', holding_en:'Procedure under Article 21 must be fair, just and reasonable. Article 14, 19 and 21 are not mutually exclusive but supplement each other.', holding_hi:'अनुच्छेद 21 के अंतर्गत प्रक्रिया न्यायपूर्ण, उचित और युक्तियुक्त होनी चाहिए। अनुच्छेद 14, 19 और 21 परस्पर पूरक हैं।' },
  { id:'j3', name:'Sharad Birdhichand Sarda v. State of Maharashtra', citation:'AIR 1984 SC 1622', court:'Supreme Court', year:1984, topics:['Circumstantial Evidence','Murder'], section:'IPC 302', holding_en:'Five Panchsheel conditions for conviction on circumstantial evidence: facts must be established; consistent with guilt; inconsistent with innocence; exclude every other hypothesis; chain must be complete.', holding_hi:'परिस्थितिजन्य साक्ष्य पर दोषसिद्धि के लिए पंचशील की पाँच शर्तें: तथ्य सिद्ध हों; अपराध के अनुरूप हों; निर्दोषता से असंगत हों; अन्य परिकल्पनाओं को अपवर्जित करें; श्रृंखला पूर्ण हो।' },
  { id:'j4', name:'Bachan Singh v. State of Punjab', citation:'AIR 1980 SC 898', court:'Supreme Court', year:1980, topics:['Death Penalty','Section 302'], section:'IPC 302', holding_en:'Death penalty constitutional but should be imposed only in rarest of rare cases. Mitigating and aggravating circumstances must be balanced.', holding_hi:'मृत्युदंड संवैधानिक है लेकिन केवल विरलतम मामलों में दिया जाना चाहिए। न्यूनकारी और वर्धक परिस्थितियों का संतुलन होना चाहिए।' },
  { id:'j5', name:'Hussainara Khatoon v. State of Bihar', citation:'AIR 1979 SC 1360', court:'Supreme Court', year:1979, topics:['Speedy Trial','Bail','Article 21'], section:'Art.21', holding_en:'Right to speedy trial is a fundamental right under Article 21. Undertrial prisoners cannot be kept in jail longer than the maximum sentence for the offence.', holding_hi:'शीघ्र विचारण का अधिकार अनुच्छेद 21 के अंतर्गत मूल अधिकार है। विचाराधीन कैदी को अपराध की अधिकतम सजा से अधिक समय तक जेल में नहीं रखा जा सकता।' },
  { id:'j6', name:'D.K. Basu v. State of West Bengal', citation:'AIR 1997 SC 610', court:'Supreme Court', year:1997, topics:['Arrest','Custody','Police Guidelines'], section:'BNSS 35', holding_en:'Laid down 11 guidelines for arrest and detention. Arrested person must be informed of grounds of arrest, right to legal aid, medical examination, and produced before magistrate within 24 hours.', holding_hi:'गिरफ्तारी और हिरासत के लिए 11 दिशानिर्देश निर्धारित किए। गिरफ्तार व्यक्ति को गिरफ्तारी के कारण, विधिक सहायता का अधिकार, चिकित्सा जांच और 24 घंटे में मजिस्ट्रेट के समक्ष पेश करना अनिवार्य।' },
  { id:'j7', name:'Mohd. Ahmed Khan v. Shah Bano Begum', citation:'AIR 1985 SC 945', court:'Supreme Court', year:1985, topics:['Maintenance','Muslim Law','Section 125'], section:'CrPC 125', holding_en:'Muslim women are entitled to maintenance under Section 125 CrPC even after divorce. Directed Parliament to frame Uniform Civil Code.', holding_hi:'मुस्लिम महिलाएं तलाक के बाद भी CrPC धारा 125 के अंतर्गत भरण-पोषण की हकदार हैं। संसद को समान नागरिक संहिता बनाने का निर्देश दिया।' },
  { id:'j8', name:'State of Maharashtra v. Madhkar Narayan', citation:'AIR 1991 SC 207', court:'Supreme Court', year:1991, topics:['Rape','Evidence','Section 376'], section:'IPC 376', holding_en:'A woman of easy virtue is also entitled to privacy. Her testimony in rape cases cannot be discarded merely on ground of her character. Her evidence must be assessed on its own merit.', holding_hi:'किसी भी स्त्री को गोपनीयता का अधिकार है। बलात्संग के मामलों में उसकी गवाही केवल उसके चरित्र के आधार पर नहीं नकारी जा सकती।' },
  { id:'j9', name:'Vishaka v. State of Rajasthan', citation:'AIR 1997 SC 3011', court:'Supreme Court', year:1997, topics:['Sexual Harassment','Workplace','Article 19'], section:'IPC 354A', holding_en:'Laid down Vishaka guidelines for prevention of sexual harassment at workplace. Defined sexual harassment. Every employer must constitute a Complaints Committee.', holding_hi:'कार्यस्थल पर यौन उत्पीड़न रोकने के लिए विशाखा दिशानिर्देश निर्धारित किए। यौन उत्पीड़न की परिभाषा दी। प्रत्येक नियोक्ता को शिकायत समिति गठित करनी होगी।' },
  { id:'j10', name:'K.S. Puttaswamy v. Union of India', citation:'(2017) 10 SCC 1', court:'Supreme Court', year:2017, topics:['Privacy','Fundamental Right','Article 21'], section:'Art.21', holding_en:'Right to privacy is a fundamental right under Article 21. Privacy includes decisional autonomy, bodily integrity, informational privacy and dignity.', holding_hi:'निजता का अधिकार अनुच्छेद 21 के अंतर्गत मूल अधिकार है। निजता में निर्णयात्मक स्वायत्तता, शारीरिक अखंडता, सूचना की निजता और गरिमा शामिल हैं।' },
  { id:'j11', name:'Aruna Shanbaug v. Union of India', citation:'(2011) 4 SCC 454', court:'Supreme Court', year:2011, topics:['Euthanasia','Article 21','Right to Die'], section:'Art.21', holding_en:'Passive euthanasia (withdrawal of life support) permitted with High Court permission. Active euthanasia not permitted. Right to die with dignity is part of Article 21.', holding_hi:'निष्क्रिय इच्छामृत्यु (जीवन रक्षक प्रणाली हटाना) उच्च न्यायालय की अनुमति से अनुमत है। सक्रिय इच्छामृत्यु अनुमत नहीं। गरिमा के साथ मरने का अधिकार अनुच्छेद 21 का हिस्सा है।' },
  { id:'j12', name:'Navtej Singh Johar v. Union of India', citation:'(2018) 10 SCC 1', court:'Supreme Court', year:2018, topics:['Section 377','LGBTQ','Decriminalization'], section:'IPC 377', holding_en:'Section 377 IPC, to the extent it criminalises consensual sexual activity between adults, is unconstitutional. Sexual orientation is an essential attribute of privacy.', holding_hi:'IPC धारा 377, जहाँ तक यह वयस्कों के बीच सहमतिपूर्ण यौन गतिविधि को आपराधिक बनाती है, असंवैधानिक है। यौन अभिविन्यास निजता की अनिवार्य विशेषता है।' },
  { id:'j13', name:'Lalman Shukla v. Gauri Dutt', citation:'(1913) 11 ALJ 489', court:'Allahabad HC', year:1913, topics:['Contract','Offer','Acceptance'], section:'Contract Act', holding_en:'Acceptance of an offer must be made with knowledge of the offer. A person cannot accept an offer he is not aware of. Contract requires consensus ad idem.', holding_hi:'प्रस्ताव को जानकर ही उसकी स्वीकृति दी जा सकती है। जिस प्रस्ताव का ज्ञान न हो उसे स्वीकार नहीं किया जा सकता।' },
  { id:'j14', name:'Mohori Bibee v. Dharmodas Ghose', citation:'(1903) 30 Cal 539', court:'Privy Council', year:1903, topics:['Minor','Contract','Void'], section:'Contract Act S.11', holding_en:'A contract by a minor is void ab initio, not merely voidable. A minor cannot be held liable on any contract, nor can he ratify a contract on attaining majority.', holding_hi:'अवयस्क का अनुबंध शुरू से ही शून्य है, केवल शून्यकरणीय नहीं। अवयस्क किसी भी अनुबंध के लिए उत्तरदायी नहीं हो सकता।' },
  { id:'j15', name:'State of U.P. v. Nahar Singh', citation:'AIR 1998 SC 1328', court:'Supreme Court', year:1998, topics:['Section 498A','Cruelty','Dowry'], section:'IPC 498A', holding_en:'Cruelty under Section 498A includes both physical and mental harassment. Single act of cruelty may be sufficient. Continuous conduct not necessary. FIR can be filed at any time.', holding_hi:'धारा 498A के अंतर्गत क्रूरता में शारीरिक और मानसिक उत्पीड़न दोनों शामिल हैं। क्रूरता का एक कार्य पर्याप्त हो सकता है।' },
  { id:'j16', name:'Arjun Panditrao Khotkar v. Kailash Kushanrao', citation:'(2020) 7 SCC 1', court:'Supreme Court', year:2020, topics:['Electronic Evidence','Section 65B','Certificate'], section:'BSA 65B', holding_en:'Certificate under Section 65B(4) is mandatory for admissibility of electronic evidence. Without the certificate, electronic record is inadmissible. The certificate must be obtained contemporaneously.', holding_hi:'धारा 65B(4) के अंतर्गत प्रमाण पत्र इलेक्ट्रॉनिक साक्ष्य की ग्राह्यता के लिए अनिवार्य है। इसके बिना इलेक्ट्रॉनिक अभिलेख अग्राह्य है।' },
  { id:'j17', name:'Arnesh Kumar v. State of Bihar', citation:'(2014) 8 SCC 273', court:'Supreme Court', year:2014, topics:['Arrest','Section 498A','498A Misuse'], section:'IPC 498A', holding_en:'Police must not arrest automatically in 498A cases. Magistrate must apply mind before authorizing detention. Seven-day notice must be issued before arrest in 498A cases where punishment is less than 7 years.', holding_hi:'धारा 498A के मामलों में पुलिस स्वतः गिरफ्तारी नहीं करेगी। मजिस्ट्रेट रिमांड से पहले विचार करेगा। 7 वर्ष से कम सजा के मामलों में गिरफ्तारी से पहले नोटिस आवश्यक।' },
  { id:'j18', name:'Satbir Singh v. State of Haryana', citation:'(2021) 6 SCC 1', court:'Supreme Court', year:2021, topics:['Dowry Death','Section 304B','Presumption'], section:'IPC 304B', holding_en:'In dowry death cases, once prosecution establishes basic facts (death within 7 years, cruelty), presumption under Section 113B Evidence Act arises against accused. Burden shifts to accused.', holding_hi:'दहेज मृत्यु में एक बार अभियोजन मूल तथ्य सिद्ध कर दे तो साक्ष्य अधिनियम धारा 113B के तहत अभियुक्त के विरुद्ध उपधारणा उठती है।' },
  { id:'j19', name:'Mithu v. State of Punjab', citation:'AIR 1983 SC 473', court:'Supreme Court', year:1983, topics:['Section 303','Death Penalty','Life Convict'], section:'IPC 303', holding_en:'Section 303 IPC (mandatory death sentence for murder by life convict) is unconstitutional as it violates Articles 14 and 21 by denying judicial discretion.', holding_hi:'IPC धारा 303 (आजीवन दंडित व्यक्ति द्वारा हत्या पर अनिवार्य मृत्युदंड) असंवैधानिक है क्योंकि यह न्यायिक विवेक को नकारकर अनुच्छेद 14 और 21 का उल्लंघन करती है।' },
  { id:'j20', name:'Lily Thomas v. Union of India', citation:'(2013) 7 SCC 653', court:'Supreme Court', year:2013, topics:['Disqualification','MPs','MLAs','Conviction'], section:'Constitution', holding_en:'MPs and MLAs convicted of any offence with 2 or more years of imprisonment are immediately disqualified from membership. Section 8(4) of Representation of People Act struck down.', holding_hi:'किसी भी अपराध में 2 या अधिक वर्ष की सजा पाने वाले सांसद और विधायक तुरंत सदस्यता से अयोग्य हो जाते हैं।' },
  { id:'j21', name:'Indian Young Lawyers Association v. State of Kerala', citation:'(2019) 11 SCC 1', court:'Supreme Court', year:2019, topics:['Sabarimala','Article 25','Religion','Women'], section:'Art.25', holding_en:'Excluding women of menstruating age from Sabarimala temple violates Articles 14, 15, 25 and 51A(e). Physiological characteristic cannot be basis for discrimination in religious practice.', holding_hi:'रजस्वला आयु की महिलाओं को सबरीमाला मंदिर से बाहर करना अनुच्छेद 14, 15, 25 और 51A(e) का उल्लंघन है।' },
  { id:'j22', name:'Union of India v. Sriharan @ Murugan', citation:'(2016) 7 SCC 1', court:'Supreme Court', year:2016, topics:['Death Penalty Commutation','Life Imprisonment','Article 72'], section:'Art.72', holding_en:'Courts can commute death penalty to imprisonment for remainder of natural life without remission. Such sentence is distinct from life imprisonment and not subject to remission.', holding_hi:'न्यायालय मृत्युदंड को शेष प्राकृतिक जीवन के कारावास में परिवर्तित कर सकते हैं जिसमें माफी नहीं होगी।' },
  { id:'j23', name:'Siddharam Satlingappa v. State of Maharashtra', citation:'(2011) 1 SCC 694', court:'Supreme Court', year:2011, topics:['Anticipatory Bail','Section 438'], section:'CrPC 438 / BNSS 438', holding_en:'Laid down 9 factors for considering anticipatory bail: nature and gravity of accusation, antecedents, possibility of fleeing, accusation prima facie true, impact on prosecution.', holding_hi:'अग्रिम जमानत विचार करने के लिए 9 कारक निर्धारित किए: आरोप की प्रकृति और गंभीरता, पूर्ववृत्त, भागने की संभावना, आरोप प्रथम दृष्टया सत्य, अभियोजन पर प्रभाव।' },
  { id:'j24', name:'Satpal Singh v. State of Punjab', citation:'(2018) 9 SCC 461', court:'Supreme Court', year:2018, topics:['Bail','Cancellation','Section 437'], section:'CrPC 437 / BNSS 437', holding_en:'Bail once granted can be cancelled on misuse of bail, interference with witnesses, non-cooperation with investigation, commission of new offence, or where earlier order was wrong.', holding_hi:'एक बार दी गई जमानत जमानत के दुरुपयोग, साक्षियों को प्रभावित करने, जांच में असहयोग, नया अपराध करने या पहले का आदेश गलत होने पर रद्द की जा सकती है।' },
  { id:'j25', name:'Gian Singh v. State of Punjab', citation:'(2012) 10 SCC 303', court:'Supreme Court', year:2012, topics:['Quashing FIR','Compounding','Section 482'], section:'CrPC 482 / BNSS 528', holding_en:'High Court can quash FIR even in non-compoundable offences if the matter is purely private and parties have settled. Power under Section 482 is wide to secure ends of justice.', holding_hi:'उच्च न्यायालय गैर-शमनीय अपराधों में भी FIR रद्द कर सकता है यदि मामला순 निजी है और पक्षकारों ने समझौता कर लिया हो।' },
  { id:'j26', name:'Lalita Kumari v. Govt. of U.P.', citation:'(2014) 2 SCC 1', court:'Supreme Court', year:2014, topics:['FIR','Mandatory Registration','Section 154'], section:'CrPC 154 / BNSS 173', holding_en:'Registration of FIR is mandatory on receiving information of cognizable offence. Police cannot conduct preliminary inquiry before registering FIR. Zero FIR is valid.', holding_hi:'संज्ञेय अपराध की सूचना मिलने पर FIR दर्ज करना अनिवार्य है। FIR से पहले प्रारंभिक जांच नहीं हो सकती। जीरो FIR वैध है।' },
  { id:'j27', name:'Mukesh v. State (NCT of Delhi) — Nirbhaya Case', citation:'(2017) 6 SCC 1', court:'Supreme Court', year:2017, topics:['Rape','Section 376','Death Penalty'], section:'IPC 376', holding_en:'Upheld death penalty for gang rape and murder. Rarest of rare doctrine applied. Crime was diabolical, brutal and showed depraved mind. No mitigating circumstances found.', holding_hi:'सामूहिक बलात्संग और हत्या के लिए मृत्युदंड बरकरार। विरलतम मामले का सिद्धांत लागू। अपराध अत्यंत क्रूर और विकृत मानसिकता का परिचायक।' },
  { id:'j28', name:'S.S. Mannan v. Union of India', citation:'(2022) 5 SCC 726', court:'Supreme Court', year:2022, topics:['UAPA','Bail','Stringent Laws'], section:'UAPA', holding_en:'Courts should not mechanically deny bail in UAPA cases. Even in cases with stringent bail provisions, Article 21 right to speedy trial must be balanced. Long incarceration without trial violates Article 21.', holding_hi:'UAPA मामलों में जमानत को यांत्रिक रूप से नहीं नकारना चाहिए। अनुच्छेद 21 के अंतर्गत शीघ्र विचारण का अधिकार संतुलित होना चाहिए।' },
  { id:'j29', name:'P. Rathinam v. Union of India', citation:'AIR 1994 SC 1844', court:'Supreme Court', year:1994, topics:['Section 309','Attempt to Suicide','Article 21'], section:'IPC 309', holding_en:'Right to life under Article 21 includes right not to live. Attempt to suicide is more a cry for help than a crime. Section 309 IPC unconstitutional (later overruled by Gian Kaur).', holding_hi:'अनुच्छेद 21 के अंतर्गत जीवन के अधिकार में न जीने का अधिकार भी शामिल है। आत्महत्या का प्रयास सहायता की पुकार है।' },
  { id:'j30', name:'Shayara Bano v. Union of India', citation:'(2017) 9 SCC 1', court:'Supreme Court', year:2017, topics:['Triple Talaq','Muslim Personal Law','Article 14'], section:'Art.14, Art.15', holding_en:'Instant triple talaq (talaq-e-biddat) is unconstitutional as it violates Articles 14 and 21. Muslim Women (Protection of Rights on Marriage) Act 2019 subsequently enacted.', holding_hi:'एकसाथ तीन तलाक (तलाक-ए-बिद्दत) असंवैधानिक है क्योंकि यह अनुच्छेद 14 और 21 का उल्लंघन करता है। बाद में मुस्लिम महिला (विवाह अधिकार संरक्षण) अधिनियम 2019 बना।' },
  // ══════════════════════════════════════════
  // CONSTITUTIONAL LAW
  // ══════════════════════════════════════════
  { id:'c1', name:'Kesavananda Bharati v. State of Kerala', citation:'(1973) 4 SCC 225', court:'Supreme Court', year:1973, topics:['Constitution','Basic Structure','Amendment'], category:'Constitutional', holding_en:'Parliament cannot amend the basic structure of the Constitution. Democracy, secularism, judicial review, federalism are basic features. Article 368 has implied limitations.', holding_hi:'संसद संविधान के मूल ढाँचे का संशोधन नहीं कर सकती। लोकतंत्र, धर्मनिरपेक्षता, न्यायिक समीक्षा, संघवाद मूल ढाँचे के हिस्से हैं। अनुच्छेद 368 पर निहित सीमाएँ हैं।' },

  { id:'c2', name:'Maneka Gandhi v. Union of India', citation:'(1978) 1 SCC 248', court:'Supreme Court', year:1978, topics:['Article 21','Personal Liberty','Due Process'], category:'Constitutional', holding_en:'Procedure under Article 21 must be fair, just and reasonable. Articles 14, 19 and 21 form a golden triangle — they are not mutually exclusive but supplement each other. Right to travel abroad is personal liberty.', holding_hi:'अनुच्छेद 21 के अंतर्गत प्रक्रिया उचित, न्यायपूर्ण और युक्तियुक्त होनी चाहिए। अनुच्छेद 14, 19 और 21 गोल्डन ट्रायंगल बनाते हैं। विदेश यात्रा का अधिकार व्यक्तिगत स्वतंत्रता में निहित है।' },

  { id:'c3', name:'Minerva Mills Ltd. v. Union of India', citation:'(1980) 3 SCC 625', court:'Supreme Court', year:1980, topics:['Constitution','Fundamental Rights','DPSP'], category:'Constitutional', holding_en:'Balance between Fundamental Rights and DPSP is basic structure. Clause removing judicial review is unconstitutional. Parliament cannot abrogate its power to amend but cannot destroy the Constitution itself.', holding_hi:'मौलिक अधिकार और नीति निदेशक तत्वों के बीच संतुलन मूल संरचना है। न्यायिक समीक्षा समाप्त करने वाला खंड असंवैधानिक है। संसद अपनी संशोधन शक्ति को समाप्त नहीं कर सकती।' },

  { id:'c4', name:'S.R. Bommai v. Union of India', citation:'(1994) 3 SCC 1', court:'Supreme Court', year:1994, topics:['Article 356','President Rule','Federalism'], category:'Constitutional', holding_en:'Proclamation of President Rule is subject to judicial review. Floor test is the only reliable test of majority. Secularism is basic structure. States cannot be dismissed for political reasons.', holding_hi:'राष्ट्रपति शासन की उद्घोषणा न्यायिक समीक्षा के अधीन है। बहुमत का एकमात्र विश्वसनीय परीक्षण फ्लोर टेस्ट है। धर्मनिरपेक्षता मूल संरचना है। राजनीतिक कारणों से राज्य सरकार नहीं हटाई जा सकती।' },

  { id:'c5', name:'Indra Sawhney v. Union of India', citation:'1992 Supp (3) SCC 217', court:'Supreme Court', year:1992, topics:['Reservation','OBC','Creamy Layer','Article 16'], category:'Constitutional', holding_en:'Reservation cannot exceed 50% (barring extraordinary circumstances). Creamy layer must be excluded from OBC reservation. Reservation is not a fundamental right. Article 16(4) is enabling, not mandatory.', holding_hi:'आरक्षण 50% से अधिक नहीं हो सकता। OBC आरक्षण से क्रीमी लेयर को बाहर करना होगा। आरक्षण मौलिक अधिकार नहीं है। अनुच्छेद 16(4) सक्षमकारी है, अनिवार्य नहीं।' },

  { id:'c6', name:'K.S. Puttaswamy v. Union of India', citation:'(2017) 10 SCC 1', court:'Supreme Court', year:2017, topics:['Privacy','Fundamental Right','Article 21'], category:'Constitutional', holding_en:'Right to privacy is a fundamental right under Article 21. Privacy includes bodily integrity, decisional autonomy, informational privacy. Aadhaar data collection must satisfy proportionality test.', holding_hi:'निजता का अधिकार अनुच्छेद 21 के अंतर्गत मूल अधिकार है। निजता में शारीरिक अखंडता, निर्णयात्मक स्वायत्तता, सूचना की निजता शामिल है। आधार डेटा संग्रह आनुपातिकता परीक्षण में उत्तीर्ण होना चाहिए।' },

  { id:'c7', name:'Kihoto Hollohan v. Zachillhu', citation:'(1992) Supp 2 SCC 651', court:'Supreme Court', year:1992, topics:['Anti-Defection','10th Schedule','Speaker'], category:'Constitutional', holding_en:'10th Schedule is valid. Speaker\'s decision is subject to judicial review but courts will not interfere at intermediate stages. Anti-defection law upholds political stability and is part of basic structure.', holding_hi:'10वीं अनुसूची वैध है। स्पीकर का निर्णय न्यायिक समीक्षा के अधीन है। दल-बदल विरोधी कानून राजनीतिक स्थिरता बनाए रखता है।' },

  { id:'c8', name:'I.R. Coelho v. State of Tamil Nadu', citation:'(2007) 2 SCC 1', court:'Supreme Court', year:2007, topics:['9th Schedule','Judicial Review','Basic Structure'], category:'Constitutional', holding_en:'Laws placed in 9th Schedule after April 24, 1973 (Kesavananda date) are subject to judicial review if they violate basic structure. No absolute immunity even for 9th Schedule laws.', holding_hi:'केशवानंद भारती निर्णय के बाद 9वीं अनुसूची में डाले कानून भी बेसिक स्ट्रक्चर टेस्ट के अधीन हैं। 9वीं अनुसूची के कानूनों को भी न्यायिक समीक्षा से पूर्ण छूट नहीं।' },

  { id:'c9', name:'L. Chandra Kumar v. Union of India', citation:'(1995) 1 SCC 400', court:'Supreme Court', year:1995, topics:['Tribunals','Article 226','Judicial Review'], category:'Constitutional', holding_en:'Tribunals are supplements to High Courts, not substitutes. Power of judicial review under Articles 226/227 cannot be ousted. High Court supervision over all tribunals is essential.', holding_hi:'न्यायाधिकरण उच्च न्यायालयों के पूरक हैं, प्रतिस्थापक नहीं। अनुच्छेद 226/227 के अंतर्गत न्यायिक समीक्षा की शक्ति नहीं छीनी जा सकती।' },

  { id:'c10', name:'Navtej Singh Johar v. Union of India', citation:'(2018) 10 SCC 1', court:'Supreme Court', year:2018, topics:['Section 377','LGBTQ','Decriminalization','Article 21'], category:'Constitutional', holding_en:'Section 377 IPC to the extent it criminalises consensual sexual activity between adults is unconstitutional. Sexual orientation is an essential attribute of privacy under Article 21.', holding_hi:'IPC धारा 377 जहाँ तक वयस्कों के बीच सहमतिपूर्ण यौन गतिविधि को आपराधिक बनाती है असंवैधानिक है। यौन अभिविन्यास अनुच्छेद 21 के अंतर्गत निजता का अनिवार्य घटक है।' },

  { id:'c11', name:'Shayara Bano v. Union of India', citation:'(2017) 9 SCC 1', court:'Supreme Court', year:2017, topics:['Triple Talaq','Muslim Personal Law','Article 14'], category:'Constitutional', holding_en:'Instant triple talaq (talaq-e-biddat) is unconstitutional as manifestly arbitrary and violates Article 14. Muslim Women (Protection of Rights on Marriage) Act 2019 subsequently enacted.', holding_hi:'एकसाथ तीन तलाक (तलाक-ए-बिद्दत) स्पष्ट रूप से मनमाना होने के कारण असंवैधानिक है और अनुच्छेद 14 का उल्लंघन करता है। बाद में मुस्लिम महिला (विवाह अधिकार संरक्षण) अधिनियम 2019 बना।' },

  { id:'c12', name:'Lily Thomas v. Union of India', citation:'(2013) 7 SCC 653', court:'Supreme Court', year:2013, topics:['Disqualification','MPs','MLAs','Conviction'], category:'Constitutional', holding_en:'MPs/MLAs convicted with 2+ years sentence are immediately disqualified. Section 8(4) of Representation of People Act (which allowed stay) was struck down as unconstitutional.', holding_hi:'2 वर्ष या अधिक की सजा पाने वाले सांसद/विधायक तुरंत अयोग्य हो जाते हैं। जनप्रतिनिधित्व अधिनियम की धारा 8(4) को असंवैधानिक घोषित किया गया।' },

  // ══════════════════════════════════════════
  // CRIMINAL LAW
  // ══════════════════════════════════════════
  { id:'cr1', name:'Sharad Birdhichand Sarda v. State of Maharashtra', citation:'AIR 1984 SC 1622', court:'Supreme Court', year:1984, topics:['Circumstantial Evidence','Murder','Panchsheel'], category:'Criminal', section:'IPC 302', holding_en:'Five Panchsheel conditions for conviction on circumstantial evidence: (1) circumstances fully established; (2) consistent with guilt of accused; (3) conclusive in nature; (4) exclude every other hypothesis; (5) chain must be complete — no innocent escape.', holding_hi:'परिस्थितिजन्य साक्ष्य पर दोषसिद्धि के पंचशील: (1) परिस्थितियाँ पूरी तरह सिद्ध हों; (2) अपराध के अनुरूप हों; (3) निर्णायक प्रकृति की हों; (4) अन्य परिकल्पनाओं को अपवर्जित करें; (5) श्रृंखला पूर्ण हो।' },

  { id:'cr2', name:'Bachan Singh v. State of Punjab', citation:'AIR 1980 SC 898', court:'Supreme Court', year:1980, topics:['Death Penalty','Rarest of Rare','Section 302'], category:'Criminal', section:'IPC 302', holding_en:'Death penalty is constitutional but should be imposed only in rarest of rare cases. Balance sheet of aggravating and mitigating circumstances must be drawn. Court must give special reasons for death penalty.', holding_hi:'मृत्युदंड संवैधानिक है लेकिन केवल विरलतम मामलों में दिया जाना चाहिए। वर्धक और न्यूनकारी परिस्थितियों का संतुलन बनाना होगा। मृत्युदंड के लिए विशेष कारण देने होंगे।' },

  { id:'cr3', name:'D.K. Basu v. State of West Bengal', citation:'(1997) 1 SCC 416', court:'Supreme Court', year:1997, topics:['Arrest','Custody','Custodial Death','Article 21'], category:'Criminal', section:'BNSS 35', holding_en:'11 mandatory guidelines for arrest: written memo with name/address; witness signature; inform family/friend; produce before magistrate within 24 hours; medical examination; right to meet lawyer; inspection memo.', holding_hi:'गिरफ्तारी के लिए 11 अनिवार्य दिशानिर्देश: नाम-पते वाला मेमो, परिवार/मित्र को सूचना, 24 घंटे में मजिस्ट्रेट के समक्ष पेशी, चिकित्सीय जाँच, वकील से मिलने का अधिकार।' },

  { id:'cr4', name:'Hussainara Khatoon v. State of Bihar', citation:'(1980) 1 SCC 81', court:'Supreme Court', year:1980, topics:['Speedy Trial','Undertrial','Article 21'], category:'Criminal', holding_en:'Right to speedy trial is a fundamental right under Article 21. Undertrial prisoners cannot be detained longer than maximum sentence for offence. State must provide legal aid to all who cannot afford lawyers.', holding_hi:'शीघ्र विचारण का अधिकार अनुच्छेद 21 के अंतर्गत मूल अधिकार है। विचाराधीन कैदी को अपराध की अधिकतम सजा से अधिक नहीं रखा जा सकता। राज्य निःशुल्क विधिक सहायता देगा।' },

  { id:'cr5', name:'Arnesh Kumar v. State of Bihar', citation:'(2014) 8 SCC 273', court:'Supreme Court', year:2014, topics:['Arrest','Section 498A','Section 41','Personal Liberty'], category:'Criminal', section:'IPC 498A / BNSS 35', holding_en:'Automatic arrest in cases punishable with less than 7 years is impermissible. Police must record reasons for necessity of arrest under Section 41 CrPC. Magistrate must apply mind before authorizing custody.', holding_hi:'7 साल से कम सजा वाले अपराधों में स्वतः गिरफ्तारी अस्वीकार्य है। पुलिस को धारा 41 के तहत गिरफ्तारी की आवश्यकता के कारण दर्ज करने होंगे। मजिस्ट्रेट रिमांड से पहले विचार करेगा।' },

  { id:'cr6', name:'Lalita Kumari v. Govt. of U.P.', citation:'(2014) 2 SCC 1', court:'Supreme Court', year:2014, topics:['FIR','Mandatory Registration','Cognizable Offence'], category:'Criminal', section:'BNSS 173', holding_en:'Registration of FIR is mandatory on receiving information of cognizable offence. No preliminary inquiry permitted before FIR registration. Zero FIR is valid. Failure to register FIR is punishable.', holding_hi:'संज्ञेय अपराध की सूचना मिलने पर FIR दर्ज करना अनिवार्य है। FIR से पहले प्रारंभिक जाँच नहीं हो सकती। जीरो FIR वैध है। FIR न दर्ज करना दंडनीय है।' },

  { id:'cr7', name:'Manu Sharma v. State (NCT of Delhi)', citation:'(2010) 6 SCC 1', court:'Supreme Court', year:2010, topics:['Fair Trial','Media Trial','Murder','Retrial'], category:'Criminal', section:'IPC 302', holding_en:'Jessica Lal murder case — retrial ordered. Media trial condemned. Hostile witnesses, political influence on prosecution condemned. Prosecution duty is to bring truth before court, not merely secure conviction.', holding_hi:'जेसिका लाल हत्याकांड — पुनः विचारण का आदेश। मीडिया ट्रायल की निंदा। गवाहों का शत्रुतापूर्ण होना और अभियोजन पर राजनीतिक प्रभाव की निंदा। अभियोजन का कर्तव्य सत्य सामने लाना है।' },

  { id:'cr8', name:'Zahira Habibullah Sheikh v. State of Gujarat', citation:'(2006) 3 SCC 374', court:'Supreme Court', year:2006, topics:['Fair Trial','Witness Protection','Retrial'], category:'Criminal', holding_en:'Best Bakery case — retrial ordered. Witnesses giving false testimony under pressure condemned. Court has duty to ensure fair trial even suo motu. Truth is foundation of justice system.', holding_hi:'बेस्ट बेकरी मामला — पुनः विचारण का आदेश। दबाव में झूठी गवाही देना न्याय का मजाक है। न्यायालय को स्वयंमेव भी fair trial सुनिश्चित करने का दायित्व है। सत्य न्यायिक प्रणाली की नींव है।' },

  { id:'cr9', name:'Hardeep Singh v. State of Punjab', citation:'(2014) 3 SCC 92', court:'Supreme Court', year:2014, topics:['Section 319','Additional Accused','CrPC','BNSS'], category:'Criminal', section:'CrPC 319 / BNSS', holding_en:'Constitutional bench: Power under Section 319 CrPC to summon additional accused can be exercised at any stage after evidence is recorded. Standard is higher than mere probability — it must appear that accused committed offence.', holding_hi:'धारा 319 CrPC के तहत साक्ष्य दर्ज होने के बाद किसी भी चरण में अतिरिक्त आरोपी को समन किया जा सकता है। मानक केवल संभावना से अधिक है — ऐसा प्रतीत होना चाहिए कि आरोपी ने अपराध किया।' },

  { id:'cr10', name:'Gian Singh v. State of Punjab', citation:'(2012) 10 SCC 303', court:'Supreme Court', year:2012, topics:['Quashing FIR','Section 482','Compromise','BNSS 528'], category:'Criminal', section:'CrPC 482 / BNSS 528', holding_en:'High Court can quash FIR in non-compoundable offences too if dispute is purely personal/private and parties have genuinely settled. Power under Section 482 is wide to secure ends of justice.', holding_hi:'उच्च न्यायालय गैर-शमनीय अपराधों में भी FIR रद्द कर सकता है यदि विवाद पूर्णतः निजी है और पक्षकारों ने वास्तव में समझौता किया हो। धारा 482 की शक्ति न्याय के उद्देश्य के लिए व्यापक है।' },

  { id:'cr11', name:'Siddharam Satlingappa Mhetre v. State of Maharashtra', citation:'(2011) 1 SCC 694', court:'Supreme Court', year:2011, topics:['Anticipatory Bail','Section 438','BNSS 438'], category:'Criminal', section:'CrPC 438 / BNSS 438', holding_en:'Nine factors for considering anticipatory bail: nature of accusation, antecedents of applicant, possibility of fleeing justice, accusation prima facie true, impact on prosecution, likelihood of tampering evidence, history of similar cases.', holding_hi:'अग्रिम जमानत के विचार के लिए 9 कारक: आरोप की प्रकृति, आवेदक के पूर्ववृत्त, भागने की संभावना, आरोप प्रथम दृष्टया सत्य, अभियोजन पर प्रभाव, साक्ष्य से छेड़छाड़ की संभावना।' },

  { id:'cr12', name:'Satpal Singh v. State of Punjab', citation:'(2018) 9 SCC 461', court:'Supreme Court', year:2018, topics:['Bail Cancellation','Section 437','Misuse of Bail'], category:'Criminal', section:'CrPC 437 / BNSS', holding_en:'Bail can be cancelled on: (1) misuse of liberty by interfering with course of justice; (2) tampering with witnesses; (3) new offence while on bail; (4) earlier court was misled.', holding_hi:'जमानत रद्द हो सकती है: (1) न्याय की प्रक्रिया में हस्तक्षेप; (2) गवाहों से छेड़छाड़; (3) जमानत पर रहते नया अपराध; (4) न्यायालय को गुमराह किया गया हो।' },

  { id:'cr13', name:'Nilabati Behera v. State of Odisha', citation:'(1993) 2 SCC 746', court:'Supreme Court', year:1993, topics:['Custodial Death','Compensation','Article 32','State Liability'], category:'Criminal', holding_en:'State is vicariously liable for custodial death. Compensation can be awarded under Article 32/226 for violation of Article 21. Constitutional tort remedy distinct from private law remedy.', holding_hi:'हिरासत में मृत्यु के लिए राज्य की विकर दायित्व है। अनुच्छेद 21 के उल्लंघन पर अनुच्छेद 32/226 के तहत प्रतिकर दिया जा सकता है।' },

  { id:'cr14', name:'Mahender Chawla v. Union of India', citation:'2018 SCC OnLine SC 2678', court:'Supreme Court', year:2018, topics:['Witness Protection','Fair Trial'], category:'Criminal', holding_en:'SC directed formulation of Witness Protection Scheme as fundamental right of witnesses. Witness protection is integral to fair trial. States must implement witness protection measures. Anonymity and relocation may be provided.', holding_hi:'उच्चतम न्यायालय ने साक्षी संरक्षण योजना बनाने का निर्देश दिया। साक्षी संरक्षण fair trial का अभिन्न अंग है। राज्यों को साक्षी संरक्षण उपाय लागू करने होंगे।' },

  { id:'cr15', name:'Selvi v. State of Karnataka', citation:'(2010) 7 SCC 263', court:'Supreme Court', year:2010, topics:['Narco Test','Lie Detector','Self Incrimination','Article 20(3)'], category:'Criminal', section:'Art.20(3)', holding_en:'Compulsory administration of narco-analysis, polygraph and brain-mapping tests violates Article 20(3) (right against self-incrimination) and Article 21 (mental privacy). Results inadmissible in evidence.', holding_hi:'अनिवार्य नार्को विश्लेषण, पॉलीग्राफ और ब्रेन मैपिंग परीक्षण अनुच्छेद 20(3) (आत्म-अभिशंसन के विरुद्ध अधिकार) और अनुच्छेद 21 का उल्लंघन करते हैं। परिणाम साक्ष्य में अग्राह्य हैं।' },

  { id:'cr16', name:'Himanshu Singh Sabharwal v. State of M.P.', citation:'AIR 2008 SC 1943', court:'Supreme Court', year:2008, topics:['Hostile Witness','Section 154','Cross Examination'], category:'Criminal', holding_en:'Prosecution can rely on other evidence even if key witness turns hostile. Court must take note of attempts to intimidate witnesses. Hostile witness evidence can be partially relied upon after careful scrutiny.', holding_hi:'मुख्य गवाह के शत्रुतापूर्ण होने पर भी अभियोजन अन्य साक्ष्यों पर निर्भर कर सकता है। गवाहों को धमकाने की कोशिशों पर न्यायालय ध्यान देगा।' },

  { id:'cr17', name:'Arjun Panditrao Khotkar v. Kailash Kushanrao', citation:'(2020) 7 SCC 1', court:'Supreme Court', year:2020, topics:['Electronic Evidence','Section 65B','Certificate'], category:'Criminal', section:'BSA 65B', holding_en:'Certificate under Section 65B(4) of Evidence Act is mandatory for admissibility of electronic records. Without the certificate, electronic evidence is inadmissible. Certificate must be obtained contemporaneously.', holding_hi:'धारा 65B(4) के अंतर्गत प्रमाण पत्र इलेक्ट्रॉनिक साक्ष्य की ग्राह्यता के लिए अनिवार्य है। प्रमाण पत्र के बिना इलेक्ट्रॉनिक अभिलेख अग्राह्य है।' },

  { id:'cr18', name:'Mithu v. State of Punjab', citation:'AIR 1983 SC 473', court:'Supreme Court', year:1983, topics:['Section 303','Death Penalty','Life Convict'], category:'Criminal', section:'IPC 303', holding_en:'Section 303 IPC (mandatory death for murder by life convict) is unconstitutional as violating Articles 14 and 21 — denies judicial discretion. Equality before law requires judicial consideration even in such cases.', holding_hi:'IPC धारा 303 (आजीवन दंडित द्वारा हत्या पर अनिवार्य मृत्युदंड) न्यायिक विवेक को नकारकर अनुच्छेद 14 और 21 का उल्लंघन करती है, इसलिए असंवैधानिक है।' },

  { id:'cr19', name:'Satbir Singh v. State of Haryana', citation:'(2021) 6 SCC 1', court:'Supreme Court', year:2021, topics:['Dowry Death','Section 304B','Presumption','Section 113B'], category:'Criminal', section:'IPC 304B', holding_en:'Once prosecution establishes: (1) death within 7 years of marriage; (2) unnatural death; (3) cruelty or harassment for dowry — presumption under Section 113B arises. Burden shifts to accused to rebut.', holding_hi:'अभियोजन द्वारा (1) विवाह के 7 वर्ष के भीतर मृत्यु; (2) असामान्य मृत्यु; (3) दहेज के लिए क्रूरता — सिद्ध होने पर धारा 113B की उपधारणा उठती है और भार अभियुक्त पर जाता है।' },

  { id:'cr20', name:'Mohammed Ajmal Kasab v. State of Maharashtra', citation:'AIR 2012 SC 3565', court:'Supreme Court', year:2012, topics:['Fair Trial','Terrorism','Death Penalty','Foreign Accused'], category:'Criminal', holding_en:'26/11 Mumbai attack case: Even foreign nationals accused of terrorism have right to fair trial. Death penalty upheld on extreme facts. State must provide legal aid to foreign nationals too. Terrorism does not affect fair trial standards.', holding_hi:'26/11 मुंबई हमला: विदेशी नागरिक भी fair trial के हकदार हैं। अत्यंत गंभीर परिस्थितियों में मृत्युदंड बरकरार। राज्य विदेशी नागरिकों को भी विधिक सहायता देगा।' },

  { id:'cr21', name:'Mukesh v. State (NCT of Delhi)', citation:'(2017) 6 SCC 1', court:'Supreme Court', year:2017, topics:['Rape','Gang Rape','Death Penalty','Section 376D'], category:'Criminal', section:'IPC 376', holding_en:'Nirbhaya case: Death penalty upheld for gang rape and murder. Crime was "diabolical, brutal and gruesome". Rarest of rare doctrine fully satisfied. Reformative theory fails for such heinous crimes. No mitigating circumstances.', holding_hi:'निर्भया मामला: सामूहिक बलात्संग और हत्या के लिए मृत्युदंड बरकरार। अपराध "शैतानी, क्रूर और वीभत्स" था। विरलतम मामले का सिद्धांत पूर्णतः संतुष्ट। कोई न्यूनकारी परिस्थिति नहीं।' },

  // ══════════════════════════════════════════
  // CIVIL & SERVICE LAW
  // ══════════════════════════════════════════
  { id:'cv1', name:'Mohori Bibee v. Dharmodas Ghose', citation:'(1903) 30 Cal 539', court:'Privy Council', year:1903, topics:['Minor','Contract','Void Ab Initio'], category:'Civil', holding_en:'A contract by a minor is void ab initio, not merely voidable. A minor cannot be held liable on any contract. Nor can he ratify a contract on attaining majority. Money paid under void contract not recoverable.', holding_hi:'अवयस्क का अनुबंध शुरू से ही शून्य है, केवल शून्यकरणीय नहीं। अवयस्क किसी भी अनुबंध के लिए उत्तरदायी नहीं हो सकता। वयस्क होने पर वह अनुबंध की पुष्टि नहीं कर सकता।' },

  { id:'cv2', name:'Lalman Shukla v. Gauri Dutt', citation:'(1913) 11 ALJ 489', court:'Allahabad HC', year:1913, topics:['Contract','Offer','Acceptance','Knowledge'], category:'Civil', holding_en:'Acceptance of an offer must be made with knowledge of the offer. A person cannot accept an offer he is not aware of. There cannot be a contract without consensus ad idem.', holding_hi:'प्रस्ताव को जानकर ही उसकी स्वीकृति दी जा सकती है। जिस प्रस्ताव का ज्ञान न हो उसे स्वीकार नहीं किया जा सकता। अनुबंध के लिए सहमति का मेल आवश्यक है।' },

  { id:'cv3', name:'Vishaka v. State of Rajasthan', citation:'(1997) 6 SCC 241', court:'Supreme Court', year:1997, topics:['Sexual Harassment','Workplace','POSH','Article 19'], category:'Civil', section:'IPC 354A', holding_en:'Laid down Vishaka guidelines (now replaced by POSH Act 2013) for prevention of sexual harassment at workplace. Defined sexual harassment. Every employer must constitute Internal Complaints Committee. CEDAW applied.', holding_hi:'कार्यस्थल पर यौन उत्पीड़न रोकने के लिए विशाखा दिशानिर्देश (अब POSH अधिनियम 2013)। यौन उत्पीड़न की परिभाषा। प्रत्येक नियोक्ता को आंतरिक शिकायत समिति गठित करनी होगी।' },

  { id:'cv4', name:'Rupa Ashok Hurra v. Ashok Hurra', citation:'(2002) 4 SCC 388', court:'Supreme Court', year:2002, topics:['Curative Petition','Review','Supreme Court'], category:'Civil', holding_en:'Curative petition is the last judicial remedy after review is dismissed. Lies for: violation of natural justice; serious procedural irregularity. Heard by 3 senior-most judges. Accepted only in rarest of rare cases.', holding_hi:'क्यूरेटिव याचिका समीक्षा खारिज होने के बाद अंतिम न्यायिक उपाय है। प्राकृतिक न्याय उल्लंघन या गंभीर प्रक्रियागत अनियमितता में दायर होती है। 3 वरिष्ठतम न्यायाधीश सुनते हैं।' },

  { id:'cv5', name:'Githa Hariharan v. Reserve Bank of India', citation:'(1999) 2 SCC 228', court:'Supreme Court', year:1999, topics:['Guardianship','Hindu Law','Gender Equality'], category:'Civil', holding_en:'"After" in Hindu Minority and Guardianship Act interpreted as "in absence of" — giving mother equal right to be natural guardian. Removes gender discrimination. Mother can be natural guardian even when father alive.', holding_hi:'हिंदू अल्पसंख्यता और संरक्षकता अधिनियम में "after" का अर्थ "अनुपस्थिति में" है — माँ को प्राकृतिक अभिभावक का समान अधिकार। लैंगिक भेदभाव समाप्त।' },

  { id:'cv6', name:'Vellore Citizens Welfare Forum v. Union of India', citation:'(1996) 5 SCC 647', court:'Supreme Court', year:1996, topics:['Environment','Precautionary Principle','Article 21','Polluter Pays'], category:'Civil', holding_en:'Precautionary Principle and Polluter Pays Principle are part of environmental law under Article 21. Sustainable development is the goal. Industries causing pollution must pay for remediation.', holding_hi:'सावधानी का सिद्धांत और प्रदूषक भुगतान सिद्धांत अनुच्छेद 21 के अंतर्गत पर्यावरण कानून का हिस्सा हैं। उद्योगों को प्रदूषण उपचार का भुगतान करना होगा।' },

  // ══════════════════════════════════════════
  // HUMAN RIGHTS & GENDER JUSTICE
  // ══════════════════════════════════════════
  { id:'hr1', name:'Aparna Bhat v. State of M.P.', citation:'2021 SCC OnLine SC 230', court:'Supreme Court', year:2021, topics:['Sexual Assault','POCSO','Bail Conditions','Gender Sensitivity'], category:'Human Rights', holding_en:'Bail conditions in sexual assault cases cannot include "rakhi tying" or meeting with victim. Such conditions are contrary to dignity of women. Judges must be gender-sensitive. Irrelevant bail conditions set aside.', holding_hi:'यौन उत्पीड़न मामलों में जमानत की शर्तों में "राखी बाँधना" या पीड़िता से मिलना शामिल नहीं हो सकता। ऐसी शर्तें महिला की गरिमा के विपरीत हैं। न्यायाधीशों को gender-sensitive होना चाहिए।' },

  { id:'hr2', name:'Patan Jamal Vali v. State of A.P.', citation:'2021 SCC OnLine SC 343', court:'Supreme Court', year:2021, topics:['Stereotype-Free Judgment','POCSO','Disability'], category:'Human Rights', holding_en:'Courts must be free from gender and disability stereotypes while writing judgments. Victim\'s mental disability does not diminish credibility of her testimony. Conviction in POCSO case upheld.', holding_hi:'निर्णय लिखते समय न्यायालय को लैंगिक और विकलांगता संबंधी रूढ़िवादिता से मुक्त होना चाहिए। पीड़िता की मानसिक विकलांगता उसकी गवाही की विश्वसनीयता कम नहीं करती।' },

  { id:'hr3', name:'Union of India v. Sriharan @ Murugan', citation:'(2016) 7 SCC 1', court:'Supreme Court', year:2016, topics:['Death Penalty Commutation','Life Imprisonment','Natural Life'], category:'Human Rights', holding_en:'Courts can commute death penalty to imprisonment for remainder of natural life without possibility of remission. Such sentence is distinct from ordinary life imprisonment and is not subject to remission.', holding_hi:'न्यायालय मृत्युदंड को शेष प्राकृतिक जीवन के कारावास में परिवर्तित कर सकते हैं जिसमें माफी की कोई संभावना नहीं होगी। यह साधारण आजीवन कारावास से अलग है।' },

  { id:'hr4', name:'Indian Young Lawyers Association v. State of Kerala', citation:'(2019) 11 SCC 1', court:'Supreme Court', year:2019, topics:['Sabarimala','Article 25','Women Rights','Religion'], category:'Human Rights', holding_en:'Excluding women of 10-50 age group from Sabarimala temple violates Articles 14, 15, 25 and 51A(e). Physiological characteristic (menstruation) cannot be basis of exclusion from religious worship.', holding_hi:'10-50 वर्ष आयु की महिलाओं को सबरीमाला मंदिर से बाहर करना अनुच्छेद 14, 15, 25 और 51A(e) का उल्लंघन है। शारीरिक विशेषता (रजस्वला) धार्मिक पूजा से बहिष्करण का आधार नहीं हो सकती।' },

  { id:'hr5', name:'Aruna Shanbaug v. Union of India', citation:'(2011) 4 SCC 454', court:'Supreme Court', year:2011, topics:['Euthanasia','Passive Euthanasia','Article 21'], category:'Human Rights', holding_en:'Passive euthanasia permitted with High Court permission. Active euthanasia not permitted. Right to die with dignity is part of Article 21. Subsequently expanded in Common Cause (2018) — advance medical directive allowed.', holding_hi:'उच्च न्यायालय की अनुमति से निष्क्रिय इच्छामृत्यु अनुमत है। सक्रिय इच्छामृत्यु अनुमत नहीं। गरिमा के साथ मरने का अधिकार अनुच्छेद 21 का हिस्सा है।' },

  // ══════════════════════════════════════════
  // JUDICIAL CONDUCT & ETHICS (From AIBE Guru Blog)
  // ══════════════════════════════════════════
  { id:'je1', name:'C. Ravichandran Iyer v. Justice A.M. Bhattacharjee', citation:'(1995) 5 SCC 457', court:'Supreme Court', year:1995, topics:['Judicial Ethics','Judicial Conduct','In-House Procedure'], category:'Judicial Ethics', holding_en:'Judicial office is a public trust. Judge must be not only legally correct but also morally above reproach. "Caesar\'s wife must be above suspicion." In-house procedure for dealing with judicial misconduct developed.', holding_hi:'न्यायिक पद एक सार्वजनिक न्यास है। न्यायाधीश को न केवल कानूनी रूप से सही बल्कि नैतिक रूप से भी निर्दोष होना चाहिए। "सीज़र की पत्नी संदेह से परे होनी चाहिए।"' },

  { id:'je2', name:'In Re: "K" — A Judicial Officer', citation:'AIR 2001 SC 972', court:'Supreme Court', year:2001, topics:['Judicial Conduct','Personal Life','Misconduct'], category:'Judicial Ethics', holding_en:'A judicial officer\'s conduct must be exemplary not only in discharge of duties but also in personal life. Standard of conduct expected from judicial officers is higher than ordinary citizens. Misconduct broadly defined.', holding_hi:'न्यायिक अधिकारी का आचरण न केवल कर्तव्य पालन में बल्कि निजी जीवन में भी अनुकरणीय होना चाहिए। न्यायिक अधिकारियों से अपेक्षित आचरण का मानक सामान्य नागरिकों से ऊँचा है।' },

  { id:'je3', name:'Election Commission of India v. M.R. Vijayabhaskar', citation:'(2021) 9 SCC 770', court:'Supreme Court', year:2021, topics:['Judicial Comments','Bench Remarks','Media'], category:'Judicial Ethics', holding_en:'Judges must avoid unnecessary or prejudicial remarks from bench, especially when proceedings are being broadcast. Judicial restraint in comments is essential. Remarks must be carefully considered before being made.', holding_hi:'न्यायाधीशों को bench पर अनावश्यक या पक्षपातपूर्ण टिप्पणी करने से बचना चाहिए, विशेष रूप से जब कार्यवाही का प्रसारण हो रहा हो। टिप्पणियों में न्यायिक संयम आवश्यक है।' },

  // ══════════════════════════════════════════
  // JUDGMENT WRITING
  // ══════════════════════════════════════════
  { id:'jw1', name:'Patan Jamal Vali v. State of A.P. (Judgment Writing)', citation:'2021 SCC OnLine SC 343', court:'Supreme Court', year:2021, topics:['Judgment Writing','Stereotype-Free','Gender Sensitivity'], category:'Judgment Writing', holding_en:'Published handbook on combating stereotypes in judicial decisions. Judges must base findings on evidence, not social prejudices. Stereotypical language about women, minorities, disabled persons to be avoided.', holding_hi:'न्यायिक निर्णयों में रूढ़िवादिता से लड़ने के लिए पुस्तिका प्रकाशित। न्यायाधीशों को साक्ष्य के आधार पर निष्कर्ष देने चाहिए, सामाजिक पूर्वाग्रहों पर नहीं।' },

  { id:'jw2', name:'Nipun Saxena v. Union of India', citation:'(2019) 2 SCC 703', court:'Supreme Court', year:2019, topics:['Sexual Offences','Victim Identity','Judgment Writing'], category:'Judgment Writing', holding_en:'Comprehensive guidelines on protection of identity and privacy of victims of sexual offences in judicial decisions. Name of victim must not be disclosed. Media orders against naming victims. Guidelines for trial procedure.', holding_hi:'यौन अपराधों की पीड़िताओं की पहचान और गोपनीयता संरक्षण पर व्यापक दिशानिर्देश। पीड़िता का नाम उजागर नहीं होना चाहिए। मीडिया के लिए नाम न प्रकाशित करने के आदेश।' },

  { id:'jw3', name:'Aparna Bhat v. State of M.P. (Judgment)', citation:'2021 SCC OnLine SC 230', court:'Supreme Court', year:2021, topics:['Judgment Writing','Gender Sensitivity','POCSO Bail'], category:'Judgment Writing', holding_en:'Issued 7-point guidelines for writing gender-sensitive judgments. Judges must not use language that stereotypes women as "promiscuous" or "of easy virtue". Evidence of victim\'s past must not be used to dilute conviction.', holding_hi:'लैंगिक संवेदनशील निर्णय लिखने के लिए 7 बिंदुओं के दिशानिर्देश। न्यायाधीश महिलाओं को रूढ़िवादी भाषा में नहीं दर्शाएँ। पीड़िता के अतीत को दोषसिद्धि कमज़ोर करने के लिए उपयोग नहीं होना चाहिए।' },

  // ══════════════════════════════════════════
  // ELECTRONIC EVIDENCE
  // ══════════════════════════════════════════
  { id:'ee1', name:'Shafhi Mohammad v. State of H.P.', citation:'(2018) 2 SCC 801', court:'Supreme Court', year:2018, topics:['Electronic Evidence','Section 65B','Certificate Relaxation'], category:'Electronic Evidence', section:'BSA 65B', holding_en:'Certificate under Section 65B(4) may be relaxed when electronic evidence is produced by a party who has no access to the device. Court can adopt flexible approach to ensure justice is not defeated by technical requirements.', holding_hi:'जब इलेक्ट्रॉनिक साक्ष्य ऐसे पक्षकार द्वारा प्रस्तुत किया जाए जिसे डिवाइस तक पहुँच नहीं है, तो धारा 65B(4) प्रमाण पत्र में छूट दी जा सकती है।' },

  { id:'ee2', name:'State v. Mohd. Afzal (Parliament Attack)', citation:'2003 SCC OnLine Del 243', court:'Delhi HC', year:2003, topics:['Electronic Evidence','CCTV','Call Records','Digital Evidence'], category:'Electronic Evidence', holding_en:'Electronic evidence including CCTV footage, call records, and computer printouts admissible subject to proof. Landmark case for admission of digital evidence in terrorism trial. Corroboration important.', holding_hi:'CCTV फुटेज, कॉल रिकॉर्ड और कंप्यूटर प्रिंटआउट सहित इलेक्ट्रॉनिक साक्ष्य सबूत के अधीन ग्राह्य है। आतंकवाद मामले में डिजिटल साक्ष्य स्वीकृति का ऐतिहासिक मामला।' },

  // ══════════════════════════════════════════
  // FAMILY & PERSONAL LAW
  // ══════════════════════════════════════════
  { id:'fl1', name:'Mohd. Ahmed Khan v. Shah Bano Begum', citation:'AIR 1985 SC 945', court:'Supreme Court', year:1985, topics:['Maintenance','Muslim Divorce','Section 125'], category:'Family Law', section:'CrPC 125', holding_en:'Muslim women entitled to maintenance under Section 125 CrPC even after irrevocable divorce. Section 125 is secular and applies to all. Called upon Parliament to enact Uniform Civil Code.', holding_hi:'मुस्लिम महिलाएं अपरिवर्तनीय तलाक के बाद भी CrPC धारा 125 के अंतर्गत भरण-पोषण की हकदार हैं। धारा 125 धर्मनिरपेक्ष है और सभी पर लागू होती है।' },

  { id:'fl2', name:'State of U.P. v. Nahar Singh', citation:'AIR 1998 SC 1328', court:'Supreme Court', year:1998, topics:['Cruelty','Section 498A','Mental Cruelty','Dowry'], category:'Family Law', section:'IPC 498A', holding_en:'Cruelty under Section 498A includes both physical and mental harassment. A single act of cruelty may be sufficient. Continuous conduct not necessary. FIR can be filed at any time within 3 years of last act.', holding_hi:'धारा 498A के अंतर्गत क्रूरता में शारीरिक और मानसिक उत्पीड़न दोनों शामिल हैं। क्रूरता का एक कार्य पर्याप्त हो सकता है। निरंतर आचरण आवश्यक नहीं।' },
];

export const searchJudgments = (q: string) => {
  const query = q.toLowerCase();
  return judgments.filter(j =>
    j.name.toLowerCase().includes(query) ||
    j.holding_en.toLowerCase().includes(query) ||
    j.holding_hi.includes(q) ||
    j.topics.some(t => t.toLowerCase().includes(query)) ||
    j.citation.toLowerCase().includes(query) ||
    (j.section && j.section.toLowerCase().includes(query)) ||
    j.year.toString().includes(query)
  );
};
