export interface Judgment {
  id: string;
  name: string;
  citation: string;
  court: string;
  year: number;
  topics: string[];
  holding_en: string;
  holding_hi: string;
  section?: string;
}

export const judgments: Judgment[] = [
  { id:'j1', name:'Kesavananda Bharati v. State of Kerala', citation:'AIR 1973 SC 1461', court:'Supreme Court', year:1973, topics:['Constitution','Basic Structure'], section:'Art.368', holding_en:'Parliament cannot amend the basic structure of the Constitution. Fundamental rights, separation of powers, judicial review form the basic structure.', holding_hi:'संसद संविधान के मूल ढाँचे का संशोधन नहीं कर सकती। मूल अधिकार, शक्तियों का पृथक्करण और न्यायिक पुनरावलोकन मूल ढाँचे का हिस्सा हैं।' },
  { id:'j2', name:'Maneka Gandhi v. Union of India', citation:'AIR 1978 SC 597', court:'Supreme Court', year:1978, topics:['Article 21','Personal Liberty','Due Process'], section:'Art.21', holding_en:'Procedure under Article 21 must be fair, just and reasonable. Article 14, 19 and 21 are not mutually exclusive but supplement each other.', holding_hi:'अनुच्छेद 21 के अंतर्गत प्रक्रिया न्यायपूर्ण, उचित और युक्तियुक्त होनी चाहिए। अनुच्छेद 14, 19 और 21 परस्पर पूरक हैं।' },
  { id:'j3', name:'Sharad Birdhichand Sarda v. State of Maharashtra', citation:'AIR 1984 SC 1622', court:'Supreme Court', year:1984, topics:['Circumstantial Evidence','Murder'], section:'IPC 302', holding_en:'Five Panchsheel conditions for conviction on circumstantial evidence: facts must be established; consistent with guilt; inconsistent with innocence; exclude every other hypothesis; chain must be complete.', holding_hi:'परिस्थितिजन्य साक्ष्य पर दोषसिद्धि के लिए पंचशील की पाँच शर्तें: तथ्य सिद्ध हों; अपराध के अनुरूप हों; निर्दोषता से असंगत हों; अन्य परिकल्पनाओं को अपवर्जित करें; श्रृंखला पूर्ण हो।' },
  { id:'j4', name:'Bachan Singh v. State of Punjab', citation:'AIR 1980 SC 898', court:'Supreme Court', year:1980, topics:['Death Penalty','Section 302'], section:'IPC 302', holding_en:'Death penalty constitutional but should be imposed only in rarest of rare cases. Mitigating and aggravating circumstances must be balanced.', holding_hi:'मृत्युदंड संवैधानिक है लेकिन केवल विरलतम मामलों में दिया जाना चाहिए। न्यूनकारी और वर्धक परिस्थितियों का संतुलन होना चाहिए।' },
  { id:'j5', name:'Hussainara Khatoon v. State of Bihar', citation:'AIR 1979 SC 1360', court:'Supreme Court', year:1979, topics:['Speedy Trial','Bail','Article 21'], section:'Art.21', holding_en:'Right to speedy trial is a fundamental right under Article 21. Undertrial prisoners cannot be kept in jail longer than the maximum sentence for the offence.', holding_hi:'शीघ्र विचारण का अधिकार अनुच्छेद 21 के अंतर्गत मूल अधिकार है। विचाराधीन कैदी को अपराध की अधिकतम सजा से अधिक समय तक जेल में नहीं रखा जा सकता।' },
  { id:'j6', name:'D.K. Basu v. State of West Bengal', citation:'AIR 1997 SC 610', court:'Supreme Court', year:1997, topics:['Arrest','Custody','Police Guidelines'], section:'BNSS 35', holding_en:'Laid down 11 guidelines for arrest and detention. Arrested person must be informed of grounds of arrest, right to legal aid, medical examination, and produced before magistrate within 24 hours.', holding_hi:'गिरफ्तारी और हिरासत के लिए 11 दिशानिर्देश निर्धारित किए। गिरफ्तार व्यक्ति को गिरफ्तारी के कारण, विधिक सहायता का अधिकार, चिकित्सा जांच और 24 घंटे में मजिस्ट्रेट के समक्ष पेश करना अनिवार्य।' },
  { id:'j7', name:'Mohd. Ahmed Khan v. Shah Bano Begum', citation:'AIR 1985 SC 945', court:'Supreme Court', year:1985, topics:['Maintenance','Muslim Law','Section 125'], section:'CrPC 125', holding_en:'Muslim women are entitled to maintenance under Section 125 CrPC even after divorce. Directed Parliament to frame Uniform Civil Code.', holding_hi:'मुस्लिम महिलाएं तलाक के बाद भी CrPC धारा 125 के अंतर्गत भरण-पोषण की हकदार हैं। संसद को समान नागरिक संहिता बनाने का निर्देश दिया।' },
  { id:'j8', name:'State of Maharashtra v. Madhkar Narayan', citation:'AIR 1991 SC 207', court:'Supreme Court', year:1991, topics:['Rape','Evidence','Section 376'], section:'IPC 376', holding_en:'A woman of easy virtue is also entitled to privacy. Her testimony in rape cases cannot be discarded merely on ground of her character. Her evidence must be assessed on its own merit.', holding_hi:'किसी भी स्त्री को गोपनीयता का अधिकार है। बलात्संग के मामलों में उसकी गवाही केवल उसके चरित्र के आधार पर नहीं नकारी जा सकती।' },
  { id:'j9', name:'Vishaka v. State of Rajasthan', citation:'AIR 1997 SC 3011', court:'Supreme Court', year:1997, topics:['Sexual Harassment','Workplace','Article 19'], section:'IPC 354A', holding_en:'Laid down Vishaka guidelines for prevention of sexual harassment at workplace. Defined sexual harassment. Every employer must constitute a Complaints Committee.', holding_hi:'कार्यस्थल पर यौन उत्पीड़न रोकने के लिए विशाखा दिशानिर्देश निर्धारित किए। यौन उत्पीड़न की परिभाषा दी। प्रत्येक नियोक्ता को शिकायत समिति गठित करनी होगी।' },
  { id:'j10', name:'K.S. Puttaswamy v. Union of India', citation:'(2017) 10 SCC 1', court:'Supreme Court', year:2017, topics:['Privacy','Fundamental Right','Article 21'], section:'Art.21', holding_en:'Right to privacy is a fundamental right under Article 21. Privacy includes decisional autonomy, bodily integrity, informational privacy and dignity.', holding_hi:'निजता का अधिकार अनुच्छेद 21 के अंतर्गत मूल अधिकार है। निजता में निर्णयात्मक स्वायत्तता, शारीरिक अखंडता, सूचना की निजता और गरिमा शामिल हैं।' },
  { id:'j11', name:'Aruna Shanbaug v. Union of India', citation:'(2011) 4 SCC 454', court:'Supreme Court', year:2011, topics:['Euthanasia','Article 21','Right to Die'], section:'Art.21', holding_en:'Passive euthanasia (withdrawal of life support) permitted with High Court permission. Active euthanasia not permitted. Right to die with dignity is part of Article 21.', holding_hi:'निष्क्रिय इच्छामृत्यु (जीवन रक्षक प्रणाली हटाना) उच्च न्यायालय की अनुमति से अनुमत है। सक्रिय इच्छामृत्यु अनुमत नहीं। गरिमा के साथ मरने का अधिकार अनुच्छेद 21 का हिस्सा है।' },
  { id:'j12', name:'Navtej Singh Johar v. Union of India', citation:'(2018) 10 SCC 1', court:'Supreme Court', year:2018, topics:['Section 377','LGBTQ','Decriminalization'], section:'IPC 377', holding_en:'Section 377 IPC, to the extent it criminalises consensual sexual activity between adults, is unconstitutional. Sexual orientation is an essential attribute of privacy.', holding_hi:'IPC धारा 377, जहाँ तक यह वयस्कों के बीच सहमतिपूर्ण यौन गतिविधि को आपराधिक बनाती है, असंवैधानिक है। यौन अभिविन्यास निजता की अनिवार्य विशेषता है।' },
  { id:'j13', name:'Lalman Shukla v. Gauri Dutt', citation:'(1913) 11 ALJ 489', court:'Allahabad HC', year:1913, topics:['Contract','Offer','Acceptance'], section:'Contract Act', holding_en:'Acceptance of an offer must be made with knowledge of the offer. A person cannot accept an offer he is not aware of. Contract requires consensus ad idem.', holding_hi:'प्रस्ताव को जानकर ही उसकी स्वीकृति दी जा सकती है। जिस प्रस्ताव का ज्ञान न हो उसे स्वीकार नहीं किया जा सकता।' },
  { id:'j14', name:'Mohori Bibee v. Dharmodas Ghose', citation:'(1903) 30 Cal 539', court:'Privy Council', year:1903, topics:['Minor','Contract','Void'], section:'Contract Act S.11', holding_en:'A contract by a minor is void ab initio, not merely voidable. A minor cannot be held liable on any contract, nor can he ratify a contract on attaining majority.', holding_hi:'अवयस्क का अनुबंध शुरू से ही शून्य है, केवल शून्यकरणीय नहीं। अवयस्क किसी भी अनुबंध के लिए उत्तरदायी नहीं हो सकता।' },
  { id:'j15', name:'State of U.P. v. Nahar Singh', citation:'AIR 1998 SC 1328', court:'Supreme Court', year:1998, topics:['Section 498A','Cruelty','Dowry'], section:'IPC 498A', holding_en:'Cruelty under Section 498A includes both physical and mental harassment. Single act of cruelty may be sufficient. Continuous conduct not necessary. FIR can be filed at any time.', holding_hi:'धारा 498A के अंतर्गत क्रूरता में शारीरिक और मानसिक उत्पीड़न दोनों शामिल हैं। क्रूरता का एक कार्य पर्याप्त हो सकता है।' },
  { id:'j16', name:'Arjun Panditrao Khotkar v. Kailash Kushanrao', citation:'(2020) 7 SCC 1', court:'Supreme Court', year:2020, topics:['Electronic Evidence','Section 65B','Certificate'], section:'BSA 65B', holding_en:'Certificate under Section 65B(4) is mandatory for admissibility of electronic evidence. Without the certificate, electronic record is inadmissible. The certificate must be obtained contemporaneously.', holding_hi:'धारा 65B(4) के अंतर्गत प्रमाण पत्र इलेक्ट्रॉनिक साक्ष्य की ग्राह्यता के लिए अनिवार्य है। इसके बिना इलेक्ट्रॉनिक अभिलेख अग्राह्य है।' },
  { id:'j17', name:'Arnesh Kumar v. State of Bihar', citation:'(2014) 8 SCC 273', court:'Supreme Court', year:2014, topics:['Arrest','Section 498A','498A Misuse'], section:'IPC 498A', holding_en:'Police must not arrest automatically in 498A cases. Magistrate must apply mind before authorizing detention. Seven-day notice must be issued before arrest in 498A cases where punishment is less than 7 years.', holding_hi:'धारा 498A के मामलों में पुलिस स्वतः गिरफ्तारी नहीं करेगी। मजिस्ट्रेट रिमांड से पहले विचार करेगा। 7 वर्ष से कम सजा के मामलों में गिरफ्तारी से पहले नोटिस आवश्यक।' },
  { id:'j18', name:'Satbir Singh v. State of Haryana', citation:'(2021) 6 SCC 1', court:'Supreme Court', year:2021, topics:['Dowry Death','Section 304B','Presumption'], section:'IPC 304B', holding_en:'In dowry death cases, once prosecution establishes basic facts (death within 7 years, cruelty), presumption under Section 113B Evidence Act arises against accused. Burden shifts to accused.', holding_hi:'दहेज मृत्यु में एक बार अभियोजन मूल तथ्य सिद्ध कर दे तो साक्ष्य अधिनियम धारा 113B के तहत अभियुक्त के विरुद्ध उपधारणा उठती है।' },
  { id:'j19', name:'Mithu v. State of Punjab', citation:'AIR 1983 SC 473', court:'Supreme Court', year:1983, topics:['Section 303','Death Penalty','Life Convict'], section:'IPC 303', holding_en:'Section 303 IPC (mandatory death sentence for murder by life convict) is unconstitutional as it violates Articles 14 and 21 by denying judicial discretion.', holding_hi:'IPC धारा 303 (आजीवन दंडित व्यक्ति द्वारा हत्या पर अनिवार्य मृत्युदंड) असंवैधानिक है क्योंकि यह न्यायिक विवेक को नकारकर अनुच्छेद 14 और 21 का उल्लंघन करती है।' },
  { id:'j20', name:'Lily Thomas v. Union of India', citation:'(2013) 7 SCC 653', court:'Supreme Court', year:2013, topics:['Disqualification','MPs','MLAs','Conviction'], section:'Constitution', holding_en:'MPs and MLAs convicted of any offence with 2 or more years of imprisonment are immediately disqualified from membership. Section 8(4) of Representation of People Act struck down.', holding_hi:'किसी भी अपराध में 2 या अधिक वर्ष की सजा पाने वाले सांसद और विधायक तुरंत सदस्यता से अयोग्य हो जाते हैं।' },
  { id:'j21', name:'Indian Young Lawyers Association v. State of Kerala', citation:'(2019) 11 SCC 1', court:'Supreme Court', year:2019, topics:['Sabarimala','Article 25','Religion','Women'], section:'Art.25', holding_en:'Excluding women of menstruating age from Sabarimala temple violates Articles 14, 15, 25 and 51A(e). Physiological characteristic cannot be basis for discrimination in religious practice.', holding_hi:'रजस्वला आयु की महिलाओं को सबरीमाला मंदिर से बाहर करना अनुच्छेद 14, 15, 25 और 51A(e) का उल्लंघन है।' },
  { id:'j22', name:'Union of India v. Sriharan @ Murugan', citation:'(2016) 7 SCC 1', court:'Supreme Court', year:2016, topics:['Death Penalty Commutation','Life Imprisonment','Article 72'], section:'Art.72', holding_en:'Courts can commute death penalty to imprisonment for remainder of natural life without remission. Such sentence is distinct from life imprisonment and not subject to remission.', holding_hi:'न्यायालय मृत्युदंड को शेष प्राकृतिक जीवन के कारावास में परिवर्तित कर सकते हैं जिसमें माफी नहीं होगी।' },
  { id:'j23', name:'Siddharam Satlingappa v. State of Maharashtra', citation:'(2011) 1 SCC 694', court:'Supreme Court', year:2011, topics:['Anticipatory Bail','Section 438'], section:'CrPC 438 / BNSS 438', holding_en:'Laid down 9 factors for considering anticipatory bail: nature and gravity of accusation, antecedents, possibility of fleeing, accusation prima facie true, impact on prosecution.', holding_hi:'अग्रिम जमानत विचार करने के लिए 9 कारक निर्धारित किए: आरोप की प्रकृति और गंभीरता, पूर्ववृत्त, भागने की संभावना, आरोप प्रथम दृष्टया सत्य, अभियोजन पर प्रभाव।' },
  { id:'j24', name:'Satpal Singh v. State of Punjab', citation:'(2018) 9 SCC 461', court:'Supreme Court', year:2018, topics:['Bail','Cancellation','Section 437'], section:'CrPC 437 / BNSS 437', holding_en:'Bail once granted can be cancelled on misuse of bail, interference with witnesses, non-cooperation with investigation, commission of new offence, or where earlier order was wrong.', holding_hi:'एक बार दी गई जमानत जमानत के दुरुपयोग, साक्षियों को प्रभावित करने, जांच में असहयोग, नया अपराध करने या पहले का आदेश गलत होने पर रद्द की जा सकती है।' },
  { id:'j25', name:'Gian Singh v. State of Punjab', citation:'(2012) 10 SCC 303', court:'Supreme Court', year:2012, topics:['Quashing FIR','Compounding','Section 482'], section:'CrPC 482 / BNSS 528', holding_en:'High Court can quash FIR even in non-compoundable offences if the matter is purely private and parties have settled. Power under Section 482 is wide to secure ends of justice.', holding_hi:'उच्च न्यायालय गैर-शमनीय अपराधों में भी FIR रद्द कर सकता है यदि मामला순 निजी है और पक्षकारों ने समझौता कर लिया हो।' },
  { id:'j26', name:'Lalita Kumari v. Govt. of U.P.', citation:'(2014) 2 SCC 1', court:'Supreme Court', year:2014, topics:['FIR','Mandatory Registration','Section 154'], section:'CrPC 154 / BNSS 173', holding_en:'Registration of FIR is mandatory on receiving information of cognizable offence. Police cannot conduct preliminary inquiry before registering FIR. Zero FIR is valid.', holding_hi:'संज्ञेय अपराध की सूचना मिलने पर FIR दर्ज करना अनिवार्य है। FIR से पहले प्रारंभिक जांच नहीं हो सकती। जीरो FIR वैध है।' },
  { id:'j27', name:'Mukesh v. State (NCT of Delhi) — Nirbhaya Case', citation:'(2017) 6 SCC 1', court:'Supreme Court', year:2017, topics:['Rape','Section 376','Death Penalty'], section:'IPC 376', holding_en:'Upheld death penalty for gang rape and murder. Rarest of rare doctrine applied. Crime was diabolical, brutal and showed depraved mind. No mitigating circumstances found.', holding_hi:'सामूहिक बलात्संग और हत्या के लिए मृत्युदंड बरकरार। विरलतम मामले का सिद्धांत लागू। अपराध अत्यंत क्रूर और विकृत मानसिकता का परिचायक।' },
  { id:'j28', name:'S.S. Mannan v. Union of India', citation:'(2022) 5 SCC 726', court:'Supreme Court', year:2022, topics:['UAPA','Bail','Stringent Laws'], section:'UAPA', holding_en:'Courts should not mechanically deny bail in UAPA cases. Even in cases with stringent bail provisions, Article 21 right to speedy trial must be balanced. Long incarceration without trial violates Article 21.', holding_hi:'UAPA मामलों में जमानत को यांत्रिक रूप से नहीं नकारना चाहिए। अनुच्छेद 21 के अंतर्गत शीघ्र विचारण का अधिकार संतुलित होना चाहिए।' },
  { id:'j29', name:'P. Rathinam v. Union of India', citation:'AIR 1994 SC 1844', court:'Supreme Court', year:1994, topics:['Section 309','Attempt to Suicide','Article 21'], section:'IPC 309', holding_en:'Right to life under Article 21 includes right not to live. Attempt to suicide is more a cry for help than a crime. Section 309 IPC unconstitutional (later overruled by Gian Kaur).', holding_hi:'अनुच्छेद 21 के अंतर्गत जीवन के अधिकार में न जीने का अधिकार भी शामिल है। आत्महत्या का प्रयास सहायता की पुकार है।' },
  { id:'j30', name:'Shayara Bano v. Union of India', citation:'(2017) 9 SCC 1', court:'Supreme Court', year:2017, topics:['Triple Talaq','Muslim Personal Law','Article 14'], section:'Art.14, Art.15', holding_en:'Instant triple talaq (talaq-e-biddat) is unconstitutional as it violates Articles 14 and 21. Muslim Women (Protection of Rights on Marriage) Act 2019 subsequently enacted.', holding_hi:'एकसाथ तीन तलाक (तलाक-ए-बिद्दत) असंवैधानिक है क्योंकि यह अनुच्छेद 14 और 21 का उल्लंघन करता है। बाद में मुस्लिम महिला (विवाह अधिकार संरक्षण) अधिनियम 2019 बना।' },
];

export const searchJudgments = (q: string) => {
  const query = q.toLowerCase();
  return judgments.filter(j =>
    j.name.toLowerCase().includes(query) ||
    j.holding_en.toLowerCase().includes(query) ||
    j.holding_hi.includes(q) ||
    j.topics.some(t => t.toLowerCase().includes(query)) ||
    j.citation.toLowerCase().includes(query) ||
    (j.section && j.section.toLowerCase().includes(query)) ||
    j.year.toString().includes(query)
  );
};
