import React from 'react';
import { FileText, Download, RotateCcw } from 'lucide-react';
import { getSettings } from './Settings';
import { format } from 'date-fns';
import { storage } from '../lib/storage';
import jsPDF from 'jspdf';

export const VakalatnaMGenerator = () => {
  const settings = getSettings();
  const cases = storage.getCases();
  const [form, setForm] = React.useState({
    clientName: '',
    clientGuardian: '',
    clientAddress: '',
    caseId: '',
    customCaseNo: '',
    court: settings.court || '',
    date: format(new Date(), 'yyyy-MM-dd'),
    caseType: 'Civil',
    before: 'Honourable Court',
  });
  const [generated, setGenerated] = React.useState(false);

  const selectedCase = cases.find(c => c.id === form.caseId);

  const caseNumber = selectedCase?.caseNumber || form.customCaseNo;
  const parties = selectedCase
    ? `${selectedCase.parties.plaintiff} vs ${selectedCase.parties.defendant}`
    : '';
  const courtName = selectedCase?.court?.name || form.court;

  const handleGenerate = () => {
    const doc = new jsPDF() as any;
    const adv = settings.advocateName || 'Advocate';
    const barNo = settings.barNumber || '___________';
    const advCity = settings.city || '___________';
    const dateStr = format(new Date(form.date + 'T00:00:00'), 'dd MMMM yyyy');

    // Header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('VAKALATNAMA', 105, 22, { align: 'center' });
    doc.setFontSize(11);
    doc.text('(Power of Attorney to Advocate)', 105, 30, { align: 'center' });

    doc.setLineWidth(0.8);
    doc.line(15, 35, 195, 35);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const lines: string[] = [
      '',
      `IN THE COURT OF: ${courtName || '_________________________'}`,
      '',
      `CASE NUMBER: ${caseNumber || '_________________________'}`,
      `CASE TYPE: ${form.caseType}`,
      parties ? `BETWEEN: ${parties}` : 'BETWEEN: _________________________ Vs _________________________',
      '',
      'KNOW ALL MEN BY THESE PRESENTS THAT I/We,',
      '',
      `${form.clientName || '_________________________'} Son/Daughter/Wife of`,
      `${form.clientGuardian || '_________________________'}`,
      `Resident of: ${form.clientAddress || '_________________________'}`,
      '',
      `(hereinafter referred to as the "Client") DO HEREBY appoint, constitute and`,
      `authorise ${adv}, Advocate, Bar Council No. ${barNo},`,
      `${advCity}, as my/our Advocate to appear, plead and act on my/our behalf in`,
      `the above-mentioned case and to do all acts, deeds and things necessary.`,
      '',
      'I/We hereby authorise the said Advocate to:',
      '(a) Appear before the Court and all proceedings thereof;',
      '(b) File petitions, applications, replies, written statements;',
      '(c) Withdraw, compromise or submit to arbitration;',
      '(d) Receive money or any documents on my/our behalf;',
      '(e) Do all other acts incidental to the above;',
      '',
      `Date: ${dateStr}`,
      `Place: ${advCity || '_____________'}`,
      '',
      '',
      '_________________________              _________________________',
      'Signature of Client                    Signature of Advocate',
      `${form.clientName || 'Client Name'}                    ${adv}`,
      '',
      `Advocate's Bar No: ${barNo}`,
      `Advocate's Address: ${settings.court || '_________________________'}`,
      '',
      'WITNESS:',
      '1. _________________________    2. _________________________',
    ];

    let y = 42;
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, 15, y);
      y += line === '' ? 4 : 7;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Legal Diary Pro', 105, 288, { align: 'center' });

    // Save
    const base64 = doc.output('datauristring').split(',')[1];
    const filename = `Vakalatnama_${form.clientName || 'Client'}_${format(new Date(), 'ddMMyyyy')}.pdf`;

    const downloadPDF = async () => {
      try {
        const { Filesystem, Directory } = await import('@capacitor/filesystem');
        await Filesystem.writeFile({ path: filename, data: base64, directory: Directory.Documents, recursive: true });
        alert(`✓ Vakalatnama saved!\nDocuments/${filename}`);
      } catch {
        const blob = new Blob([Uint8Array.from(atob(base64), c => c.charCodeAt(0))], { type: 'application/pdf' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = filename; a.click();
        setTimeout(() => URL.revokeObjectURL(url), 3000);
      }
    };
    downloadPDF();
    setGenerated(true);
  };

  const F = ({ label, children }: { label: string; children: React.ReactNode }) => (
    <div className="space-y-1.5">
      <label className="text-xs font-bold text-zinc-500 uppercase tracking-widest block">{label}</label>
      {children}
    </div>
  );

  const inp = (key: keyof typeof form, placeholder: string, type = 'text') => (
    <input type={type} placeholder={placeholder} value={(form as any)[key]}
      onChange={e => setForm({ ...form, [key]: e.target.value })}
      className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green transition-colors" />
  );

  return (
    <div className="flex flex-col h-full">
      <div className="p-5 shrink-0" style={{ background: 'linear-gradient(135deg, #0a0f1e, #14532d)' }}>
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-legal-gold/20 border border-legal-gold/30 flex items-center justify-center">
            <FileText size={24} className="text-legal-gold" />
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-[0.3em] font-bold text-legal-gold">Auto Generate</p>
            <h2 className="text-2xl font-display font-bold text-white">Vakalatnama</h2>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-4">
        <div className="bg-white rounded-3xl border border-zinc-200 p-6 shadow-sm space-y-4">
          <h3 className="font-bold text-zinc-700 text-xs uppercase tracking-widest">Advocate Details (Auto-filled)</h3>
          <div className="grid grid-cols-2 gap-3 p-4 bg-zinc-50 rounded-2xl">
            <div><p className="text-[10px] text-zinc-400 uppercase font-bold">Advocate</p><p className="font-bold text-sm">{settings.advocateName || 'Set in Settings'}</p></div>
            <div><p className="text-[10px] text-zinc-400 uppercase font-bold">Bar No.</p><p className="font-bold text-sm">{settings.barNumber || 'Set in Settings'}</p></div>
            <div className="col-span-2"><p className="text-[10px] text-zinc-400 uppercase font-bold">Court</p><p className="font-bold text-sm">{settings.court || 'Set in Settings'}</p></div>
          </div>
        </div>

        <div className="bg-white rounded-3xl border border-zinc-200 p-6 shadow-sm space-y-4">
          <h3 className="font-bold text-zinc-700 text-xs uppercase tracking-widest">Client / Party Details</h3>
          <F label="Client Full Name"><input placeholder="Ramesh Kumar Sharma" value={form.clientName} onChange={e => setForm({...form, clientName: e.target.value})} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green" /></F>
          <F label="Son/Daughter/Wife of"><input placeholder="Suresh Kumar Sharma" value={form.clientGuardian} onChange={e => setForm({...form, clientGuardian: e.target.value})} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green" /></F>
          <F label="Client Address"><textarea placeholder="House No., Street, City, State" value={form.clientAddress} onChange={e => setForm({...form, clientAddress: e.target.value})} rows={2} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green resize-none" /></F>
        </div>

        <div className="bg-white rounded-3xl border border-zinc-200 p-6 shadow-sm space-y-4">
          <h3 className="font-bold text-zinc-700 text-xs uppercase tracking-widest">Case Details</h3>
          <F label="Select Existing Case (Optional)">
            <select value={form.caseId} onChange={e => setForm({...form, caseId: e.target.value})} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green">
              <option value="">-- Type manually below --</option>
              {cases.map(c => <option key={c.id} value={c.id}>{c.caseNumber} — {c.parties.plaintiff} vs {c.parties.defendant}</option>)}
            </select>
          </F>
          {!form.caseId && (
            <F label="Case Number (Manual)"><input placeholder="Civil Suit No. 123/2024" value={form.customCaseNo} onChange={e => setForm({...form, customCaseNo: e.target.value})} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green" /></F>
          )}
          <div className="grid grid-cols-2 gap-3">
            <F label="Case Type">
              <select value={form.caseType} onChange={e => setForm({...form, caseType: e.target.value})} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green">
                {['Civil','Criminal','Family','Writ','Execution','Appeal','Revision','Others'].map(t => <option key={t}>{t}</option>)}
              </select>
            </F>
            <F label="Date"><input type="date" value={form.date} onChange={e => setForm({...form, date: e.target.value})} className="w-full px-4 py-3 rounded-2xl border border-zinc-200 text-sm outline-none focus:border-legal-green" /></F>
          </div>
        </div>

        <button onClick={handleGenerate}
          disabled={!form.clientName}
          className="w-full flex items-center justify-center gap-2 py-4 bg-legal-green text-white rounded-2xl font-bold shadow-lg shadow-legal-green/20 hover:opacity-90 disabled:opacity-40 transition-all">
          <Download size={20} />
          {generated ? '✓ Downloaded! Generate Again' : 'Generate & Download Vakalatnama PDF'}
        </button>

        {!settings.advocateName && (
          <p className="text-center text-xs text-red-500">⚠️ Settings mein Advocate Name & Bar Number add karein</p>
        )}
      </div>
    </div>
  );
};
